apiVersion: apps/v1
kind: Deployment
metadata:
  name: hafoza
  namespace: hafoza
  labels:
    app: hafoza
    app.kubernetes.io/managed-by: devops-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hafoza
  template:
    metadata:
      labels:
        app: hafoza
    spec:
      containers:
        - name: hafoza
          image: 997206200726.dkr.ecr.us-east-1.amazonaws.com/b0e15-2a1e-4190-adb4-5e86f5387b1b:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 800Mi
            limits:
              cpu: 1
              memory: 1Gi
