apiVersion: v1
kind: LimitRange
metadata:
  name: hafoza-limits
  namespace: hafoza
  labels:
    app: hafoza
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 500m
        memory: 800Mi
      default:
        cpu: 1
        memory: 1Gi
