apiVersion: v1
kind: Service
metadata:
  name: hafoza
  namespace: hafoza
  labels:
    app: hafoza
spec:
  type: ClusterIP
  selector:
    app: hafoza
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
