apiVersion: v1
kind: Service
metadata:
  name: hafoza
  namespace: hafoza
  labels:
    app: hafoza
spec:
  type: ClusterIP
  selector:
    app: hafoza
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
