apiVersion: v1
kind: Service
metadata:
  name: lastone
  namespace: lastone
  labels:
    app: lastone
spec:
  type: ClusterIP
  selector:
    app: lastone
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
